// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlP24z-EpcO6akBHouRa9vgmTPLMOXPns',
    appId: '1:476068595705:web:e9331d94585bccf0dc5f28',
    messagingSenderId: '476068595705',
    projectId: 'eventradar-371df',
    authDomain: 'eventradar-371df.firebaseapp.com',
    storageBucket: 'eventradar-371df.appspot.com',
    measurementId: 'G-TVXDM02SBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyD-_jr9vna6gJd9WG7tdXNXK0z2z-hs',
    appId: '1:476068595705:android:79b51d20cc2a6b3adc5f28',
    messagingSenderId: '476068595705',
    projectId: 'eventradar-371df',
    storageBucket: 'eventradar-371df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN-eoWz5JlSj5KCwQEpmHXOzd0lva8yo0',
    appId: '1:476068595705:ios:a595814a5ed0d36cdc5f28',
    messagingSenderId: '476068595705',
    projectId: 'eventradar-371df',
    storageBucket: 'eventradar-371df.appspot.com',
    iosBundleId: 'com.example.eventRadar2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN-eoWz5JlSj5KCwQEpmHXOzd0lva8yo0',
    appId: '1:476068595705:ios:0f01708366408d8bdc5f28',
    messagingSenderId: '476068595705',
    projectId: 'eventradar-371df',
    storageBucket: 'eventradar-371df.appspot.com',
    iosBundleId: 'com.example.eventRadar2.RunnerTests',
  );
}
